add missing stdio.h
Fix:

main.cpp: In function ‘int main(int, char**)’:
main.cpp:81:33: error: ‘fopen’ was not declared in this scope
main.cpp:110:34: error: ‘fprintf’ was not declared in this scope
main.cpp:112:78: error: ‘fprintf’ was not declared in this scope
main.cpp:120:60: error: ‘printf’ was not declared in this scope
main.cpp:125:11: error: ‘fclose’ was not declared in this scope